import { useEffect, useState } from 'react';
import { listBatches, batchTeacherApi, type BatchListItem, type TeacherAssignment } from '../../batches/api/batches.api';
import { instructorError, type Instructor } from '../api/instructors.api';
export default function InstructorAssignmentsPanel({ record, canManage, onChanged }: { record: Instructor; canManage: boolean; onChanged: () => Promise<void> }) {
 const [batches,setBatches] = useState<BatchListItem[]>([]);
 const [batchId,setBatchId] = useState('');
 const [role,setRole] = useState<TeacherAssignment['teachingRole']>('instructor');
 const [error,setError] = useState('');
 const [busy,setBusy] = useState(false);
 const [moves,setMoves] = useState<Record<string,string>>({});
 const [ready,setReady] = useState(false);
 const assignments=record.assignments ?? [];
 useEffect(()=>{let active=true; (async()=>{const all:BatchListItem[]=[];let page=1;while(true){const result=await listBatches({page,pageSize:100});all.push(...result.items);if(!result.pagination.hasNext)break;page++;}if(active){setBatches(all.filter(batch=>batch.status==='active'||batch.status==='upcoming'));setReady(true);}})().catch(err=>{if(active)setError(instructorError(err));});return()=>{active=false};},[]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await onChanged();return true;}catch(err){setError(instructorError(err));return false;}finally{setBusy(false);}}
 const enabled=canManage&&!record.archivedAt&&record.status==='active';
 return <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">Assigned courses & cohorts</h2>{error&&<p role="alert" className="mb-3 text-sm text-rose-600">{error}</p>}
 <div className="space-y-3">{assignments.map(entry=><div key={entry.id} className="flex flex-wrap items-center gap-3 rounded-lg border p-3"><div className="mr-auto"><p>{entry.courseTitle}</p><p className="text-xs text-slate-500">{entry.cohort} ? {entry.learnerCount} learners</p></div><select aria-label={`Teaching role in ${entry.cohort}`} disabled={!enabled||busy} value={entry.teachingRole} onChange={event=>void run(()=>batchTeacherApi.role(entry.id,{userId:record.userId,teachingRole:event.target.value as TeacherAssignment['teachingRole']}))}><option value="instructor">Instructor</option><option value="co_instructor">Co-instructor</option></select>{enabled&&<><select aria-label={`Move ${entry.cohort} assignment to`} disabled={busy||!ready} value={moves[entry.id]||''} onChange={event=>setMoves(current=>({...current,[entry.id]:event.target.value}))}><option value="">Move to another cohort</option>{batches.filter(batch=>!assignments.some(item=>item.id===batch.id)).map(batch=><option key={batch.id} value={batch.id}>{batch.name} | {batch.courseTitle}</option>)}</select><button disabled={busy||!moves[entry.id]} onClick={()=>void run(()=>batchTeacherApi.move(entry.id,{userId:record.userId,teachingRole:entry.teachingRole},moves[entry.id]))}>Move</button><button disabled={busy} className="text-sm text-rose-600" onClick={()=>{if(window.confirm(`Remove ${record.name} from ${entry.cohort}?`))void run(()=>batchTeacherApi.remove(entry.id,record.userId));}}>Remove</button></>}</div>)}</div>
 {!assignments.length&&<p className="text-sm text-slate-500">No assigned courses or cohorts.</p>}
 {enabled?<form className="mt-5 flex flex-wrap gap-3" onSubmit={event=>{event.preventDefault();void run(()=>batchTeacherApi.add(batchId,{userId:record.userId,teachingRole:role})).then(saved=>{if(saved)setBatchId('');});}}><select required aria-label="Course and cohort" disabled={busy||!ready} value={batchId} onChange={event=>setBatchId(event.target.value)}><option value="">{ready?'Select a cohort':'Loading cohorts...'}</option>{batches.filter(batch=>!assignments.some(item=>item.id===batch.id)).map(batch=><option key={batch.id} value={batch.id}>{batch.name} | {batch.courseTitle}</option>)}</select><select aria-label="New assignment teaching role" disabled={busy} value={role} onChange={event=>setRole(event.target.value as TeacherAssignment['teachingRole'])}><option value="instructor">Instructor</option><option value="co_instructor">Co-instructor</option></select><button disabled={busy||!batchId} className="rounded-lg bg-[#0C5A69] px-4 py-2 text-sm text-white">Add assignment</button></form>:<p className="mt-4 text-sm text-slate-500">Manual assignments require an active instructor account. Pending invitations retain their initial assignment; drafts retain a planned selection.</p>}
 <p className="mt-4 text-xs text-slate-500">Teaching roles apply to this batch. Workspace roles stay unchanged.</p></section>;
}
