import { ArrowUpRight, Download, Flag, MessageSquareText, Plus, Star } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { reviews, tone } from "./reviews-demo";
import { Stars, StatusPill } from "./review-ui";

const metrics = [
  { label: "Total reviews", value: "12,486", change: "+18.2%", icon: MessageSquareText },
  { label: "Average rating", value: "4.7", change: "+0.3", icon: Star },
  { label: "Response rate", value: "94.8%", change: "+6.1%", icon: ArrowUpRight },
  { label: "Needs attention", value: "28", change: "-12.8%", icon: Flag },
];
const bars = [42, 64, 51, 78, 58, 88, 69];

export default function AdminReviewsDashboardPage() {
  const navigate = useNavigate();
  return <main className="mx-auto max-w-[1500px] space-y-6 p-5 md:p-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start">
      <div><h1 className="text-2xl font-bold text-slate-950">Reviews Dashboard</h1><p className="mt-1 text-sm text-slate-500">Monitor customer sentiment, response performance, and review operations in one place.</p></div>
      <div className="flex gap-2"><button onClick={() => navigate("/admin/reviews/new")} className="inline-flex items-center gap-2 rounded-lg bg-[#0c5a69] px-3.5 py-2 text-sm font-semibold text-white hover:bg-[#084b57]"><Plus size={16}/> Add review</button><button className="inline-flex items-center gap-2 rounded-lg border border-sky-200 bg-white px-3.5 py-2 text-sm font-semibold text-sky-700"><Download size={16}/> Export data</button></div>
    </div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, change, icon: Icon }) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-medium text-slate-500">{label}</p><span className="rounded-md bg-teal-50 p-1.5 text-teal-600"><Icon size={15}/></span></div><div className="mt-3 flex items-end gap-2"><strong className="text-2xl text-slate-950">{value}</strong><span className="mb-1 text-xs font-semibold text-emerald-600">{change}</span></div></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-2">
      <Chart title="Reviews over time" subtitle="Last 30 days" legend />
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold text-slate-900">Sentiment</h2><p className="text-xs text-slate-500">Last 30 days</p></div><span className="rounded bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">4.7 avg</span></div><div className="mt-5 flex flex-col items-center justify-center gap-5 sm:flex-row"><div className="grid h-40 w-40 place-items-center rounded-full" style={{ background: "conic-gradient(#0d8179 0 85%, #f8a51c 85% 95%, #ef5c5c 95% 100%)" }}><div className="grid h-28 w-28 place-items-center rounded-full bg-white text-center"><span className="text-xs text-slate-500">Sentiment</span><strong className="text-2xl text-slate-900">85%</strong></div></div><div className="space-y-3 text-sm"><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#0d8179]"/>Positive <b className="ml-1">85%</b></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-400"/>Neutral <b className="ml-1">10%</b></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-rose-500"/>Negative <b className="ml-1">5%</b></p></div></div></div>
      <Chart title="Response performance" subtitle="Avg response time" />
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">Reviewers</h2><p className="text-xs text-slate-500">Top contributors</p></div><span className="text-xs text-slate-500">128 reviewers</span></div><div className="mt-4 space-y-4">{reviews.map((review, index) => <div key={review.id} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-500">{review.reviewer.split(" ").map((part) => part[0]).join("")}</span><span className="min-w-0 flex-1 truncate text-sm font-medium text-slate-700">{review.reviewer}</span><span className="text-xs text-slate-500">{1240 - index * 150}</span><span className="h-1.5 w-20 rounded bg-slate-100"><i className="block h-full rounded bg-teal-600" style={{ width: `${90 - index * 9}%` }}/></span></div>)}</div></div>
    </section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Recent reviews</h2><p className="text-xs text-slate-500">Latest activity</p></div><button onClick={() => navigate("/admin/reviews")} className="text-sm font-semibold text-[#0c5a69]">View all ?</button></div><div className="mt-3 divide-y divide-slate-100">{reviews.slice(0, 5).map((review) => <button key={review.id} onClick={() => navigate(`/admin/reviews/${review.id}`)} className="flex w-full items-center gap-3 py-3 text-left hover:bg-slate-50"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-500">{review.reviewer[0]}</span><span className="min-w-0 flex-1"><b className="block text-sm text-slate-800">{review.reviewer}</b><span className="block truncate text-xs text-slate-500">{review.text}</span></span><Stars value={review.rating} compact/><StatusPill value={review.status} className={tone[review.status]}/><span className="hidden text-xs text-slate-500 sm:inline">{review.date}</span></button>)}</div></section>
  </main>;
}
function Chart({ title, subtitle, legend }: { title: string; subtitle: string; legend?: boolean }) { return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><h2 className="font-bold text-slate-900">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div>{legend && <span className="text-xs text-slate-500"><i className="mr-1 inline-block h-2 w-2 rounded-full bg-teal-600"/>Published <i className="ml-3 mr-1 inline-block h-2 w-2 rounded-full bg-rose-500"/>Flagged</span>}</div><div className="mt-8 flex h-40 items-end gap-3 border-b border-l border-slate-100 px-4">{bars.map((height, index) => <div key={index} className="group flex flex-1 flex-col justify-end gap-1"><i className="block rounded-t bg-teal-500/85 transition group-hover:bg-teal-600" style={{ height: `${height}%` }}/>{legend && <i className="block rounded-t bg-rose-400/70" style={{ height: `${Math.max(10, height - 15)}%` }}/>}</div>)}</div><div className="mt-3 flex justify-between px-4 text-xs text-slate-400"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div> }
