import { Filter, Search, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { adminApi, adminError, type AdminTicket } from "../api/admin.api";

export default function AdminTicketsListPage() {
  const [params] = useSearchParams(); const mine = params.get("view") === "assigned"; const [items, setItems] = useState<AdminTicket[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await adminApi.tickets({ page, pageSize: 20, assignedToMe: mine || undefined, search: search || undefined, status: status || undefined, priority: priority || undefined }); setItems(result.items); setTotal(result.pagination.total); } catch (e) { setError(adminError(e)); } finally { setLoading(false); } }, [mine, page, priority, search, status]); useEffect(() => { void load(); }, [load]); const pages = Math.max(1, Math.ceil(total / 20));
  return <main className="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-[#0C5A69]">Customer support</p><h1 className="mt-1 text-2xl font-bold">{mine ? "My assigned tickets" : "Tickets"}</h1><p className="mt-1 text-sm text-slate-500">Review tenant issues, assign administrators, and track resolutions.</p></div><Link to={mine ? "/admin/tickets" : "/admin/tickets?view=assigned"} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#0C5A69] px-4 py-2 text-sm font-semibold text-white"><SlidersHorizontal size={16} /> {mine ? "All tickets" : "My assigned tickets"}</Link></div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 lg:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm" placeholder="Search ticket..." /></label><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-lg border px-3 py-2 text-sm"><option value="">All statuses</option>{["open", "assigned", "in_progress", "waiting_for_user", "pending", "escalated", "resolved", "closed"].map((value) => <option key={value}>{value}</option>)}</select><select value={priority} onChange={(e) => { setPriority(e.target.value); setPage(1); }} className="rounded-lg border px-3 py-2 text-sm"><option value="">All priorities</option>{["low", "medium", "high", "critical", "urgent"].map((value) => <option key={value}>{value}</option>)}</select><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Filter size={16} /> Apply</button></div>
      {loading ? <State text="Loading tickets…" /> : error ? <State text={error} retry={load} /> : <><div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Ticket</th><th className="p-4">Tenant / requester</th><th className="p-4">Status</th><th className="p-4">Priority</th><th className="p-4">Assigned admin</th><th className="p-4">Updated</th></tr></thead><tbody className="divide-y">{items.map((ticket) => <tr key={ticket.id}><td className="p-4"><Link to={`/admin/tickets/${ticket.id}`} className="font-bold text-[#0C5A69]">#{ticket.ticketNumber}</Link><p className="mt-1 max-w-xs truncate">{ticket.title}</p></td><td className="p-4 text-xs text-slate-600"><p>{ticket.tenantId}</p><p className="mt-1">{ticket.raisedByUserId}</p></td><td className="p-4 capitalize">{ticket.status}</td><td className="p-4 capitalize">{ticket.priority}</td><td className="p-4 text-slate-600">{ticket.assignedAdminUserId || "Unassigned"}</td><td className="p-4 text-slate-500">{new Date(ticket.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div>{items.length === 0 && <State text="No tickets match the selected filters." />}</>}
      <div className="flex justify-between border-t p-4 text-sm text-slate-500"><span>Page {page} of {pages} · {total} tickets</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Previous</button><button disabled={page >= pages} onClick={() => setPage(page + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">Next</button></div></div>
    </section></main>;
}
function State({ text, retry }: { text: string; retry?: () => void }) { return <div className="p-10 text-center text-sm text-slate-500"><p>{text}</p>{retry && <button onClick={retry} className="mt-3 rounded border px-3 py-1.5 text-[#0C5A69]">Retry</button>}</div>; }
