import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { MailPlus, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { adminApi, adminError, type AdminAccessRole, type AdminTeamMember, type AdminTenantInvitation, type Pagination } from '../api/admin.api';
import { useAdminSession } from '../AdminSession';

type Tab = 'members' | 'invitations' | 'roles';
type Permission = { key: string; group: string; label: string; description: string };
const input = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[#0C5A69]/25';
const primary = 'inline-flex items-center justify-center gap-2 rounded-lg bg-[#0C5A69] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#084855] disabled:opacity-50';
const secondary = 'inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50';
const valueName = (value: unknown) => typeof value === 'string' || !value ? '—' : (value as { name?: string }).name ?? '—';

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-bold">{title}</h2><button type="button" onClick={close}><X /></button></div>{children}</div></div>; }
function Field({ label, value, change, type = 'text' }: { label: string; value: string; change: (value: string) => void; type?: string }) { return <label className="block text-sm font-semibold">{label}<input required type={type} value={value} className={input} onChange={(event) => change(event.target.value)} /></label>; }
function Table({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map((x) => <th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td className="p-4" key={j}>{cell}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <p className="p-10 text-center text-slate-500">No records found.</p>}</div>; }

export default function AdminTeamManagement() {
  const { can } = useAdminSession(); const [tab, setTab] = useState<Tab>('members'); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [reload, setReload] = useState(0); const [meta, setMeta] = useState<Pagination | null>(null); const [error, setError] = useState('');
  const [members, setMembers] = useState<AdminTeamMember[]>([]); const [invites, setInvites] = useState<AdminTenantInvitation[]>([]); const [roles, setRoles] = useState<AdminAccessRole[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [modal, setModal] = useState<'invite' | 'role' | null>(null);
  const [roleForm, setRoleForm] = useState({ name: '', description: '', permissions: [] as string[] }); const [editingRole, setEditingRole] = useState<AdminAccessRole | null>(null); const [inviteForm, setInviteForm] = useState({ name: '', email: '', accessRoleId: '', permissions: [] as string[] });
  const manage = can('team:manage') || can('tenant_access_role:manage') || can('tenant_invitation:manage'); const query = { page, pageSize: 10, search: search || undefined, status: status || undefined }; const refresh = () => setReload((x) => x + 1);
  useEffect(() => { setPage(1); }, [tab, search, status]);
  useEffect(() => { let active = true; const request = tab === 'members' ? adminApi.teamMembers(query) : tab === 'invitations' ? adminApi.invitations(query) : adminApi.accessRoles(query); request.then((result) => { if (!active) return; if (tab === 'members') setMembers(result.items as AdminTeamMember[]); if (tab === 'invitations') setInvites(result.items as AdminTenantInvitation[]); if (tab === 'roles') setRoles(result.items as AdminAccessRole[]); setMeta(result.pagination); setError(''); }).catch((e) => active && setError(adminError(e))); return () => { active = false; }; }, [tab, page, search, status, reload]);
  useEffect(() => { adminApi.accessRoles({ page: 1, pageSize: 100 }).then((x) => setRoles(x.items)).catch(() => undefined); adminApi.teamPermissions().then((x) => setPermissions(x.permissions as Permission[])).catch(() => undefined); }, [reload]);
  const invite = async (event: FormEvent) => { event.preventDefault(); try { await adminApi.createInvitation({ ...inviteForm, name: inviteForm.name.trim(), email: inviteForm.email.trim().toLowerCase() } as never); toast.success('Invitation sent. A secure password setup link was emailed.'); setModal(null); refresh(); } catch (e) { toast.error(adminError(e)); } };
  const saveRole = async (event: FormEvent) => { event.preventDefault(); try { if (editingRole) await adminApi.updateAccessRole(editingRole.id, roleForm); else await adminApi.createAccessRole(roleForm); toast.success(editingRole ? 'Access role updated.' : 'Access role created.'); setModal(null); setEditingRole(null); refresh(); } catch (e) { toast.error(adminError(e)); } };
  const deleteRole = async (role: AdminAccessRole) => { if (!window.confirm(`Delete role "${role.name}"?`)) return; try { await adminApi.deleteAccessRole(role.id); toast.success('Access role deleted.'); refresh(); } catch (e) { toast.error(adminError(e)); } };
  const revoke = async (id: string) => { try { await adminApi.revokeInvitation(id); toast.success('Invitation revoked.'); refresh(); } catch (e) { toast.error(adminError(e)); } };
  const selectRole = (accessRoleId: string) => { const role = roles.find((x) => x.id === accessRoleId); setInviteForm((form) => ({ ...form, accessRoleId, permissions: role?.permissions ?? [] })); };
  const tabItems: Array<[Tab, string]> = [['members', 'Members'], ['invitations', 'Invitations'], ['roles', 'Roles & permissions']];
  return <main className="mx-auto max-w-7xl space-y-6 px-5 py-8 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#0C5A69]">Platform administration</p><h1 className="mt-2 text-3xl font-bold">Team Management</h1><p className="mt-1 text-sm text-slate-500">Invite users and manage their portal access.</p></div>{manage && <button className={primary} onClick={() => { const role = roles.find((x) => !x.isSystem); setInviteForm({ name: '', email: '', accessRoleId: role?.id ?? '', permissions: role?.permissions ?? [] }); setModal('invite'); }}><MailPlus size={17} /> Invite user</button>}</header>
    <div className="grid gap-3 sm:grid-cols-3">{tabItems.map(([id, label]) => <button key={id} onClick={() => { setTab(id); setStatus(''); }} className={`rounded-xl border p-4 text-left font-semibold ${tab === id ? 'border-[#0C5A69] bg-[#e7f2f4]' : 'bg-white'}`}>{label}</button>)}</div>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap gap-3 border-b p-4"><label className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${input} !mt-0 pl-10`} placeholder={`Search ${tab}...`} /></label>{tab !== 'roles' && <select className={`${input} !mt-0 w-44`} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{tab === 'invitations' ? <><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="expired">Expired</option><option value="revoked">Revoked</option></> : <><option value="active">Active</option><option value="inactive">Inactive</option></>}</select>}{tab === 'roles' && manage && <button className={primary} onClick={() => { setEditingRole(null); setRoleForm({ name: '', description: '', permissions: [] }); setModal('role'); }}><Plus size={16} /> Create role</button>}</div>{error && <p className="m-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
      {tab === 'members' && <Table headers={['User', 'Role', 'Permissions', 'Status']} rows={members.map((x) => [valueName(x.tenantId), valueName(x.accessRoleId), `${x.permissions.length} permissions`, x.status])} />}
      {tab === 'invitations' && <Table headers={['User', 'Work email', 'Role', 'Status', 'Actions']} rows={invites.map((x) => [x.name, x.email, valueName(x.accessRoleId), x.status, x.status === 'pending' && <div className="flex gap-3"><button title="Resend" onClick={() => void adminApi.resendInvitation(x.id).then(() => { toast.success('Invitation resent.'); refresh(); }).catch((e) => toast.error(adminError(e)))}><RefreshCw size={16} /></button>{manage && <button className="text-red-600" title="Revoke" onClick={() => void revoke(x.id)}><Trash2 size={16} /></button>}</div>])} />}
      {tab === 'roles' && <Table headers={['Role', 'Description', 'Permissions', 'Type', 'Actions']} rows={roles.map((x) => [x.name, x.description || '—', `${x.permissions.length} permissions`, x.isSystem ? 'System' : 'Custom', x.isSystem ? 'Locked' : <div className="flex gap-3"><button title="Edit role" onClick={() => { setEditingRole(x); setRoleForm({ name: x.name, description: x.description || '', permissions: [...x.permissions] }); setModal('role'); }}><Pencil size={16} /></button><button title="Delete role" className="text-red-600" onClick={() => void deleteRole(x)}><Trash2 size={16} /></button></div>])} />}
      {meta && <div className="flex items-center justify-between border-t p-4 text-sm"><span>{meta.total} results · Page {page} of {Math.max(1, meta.totalPages)}</span><div className="flex gap-2"><button className={secondary} disabled={!meta.hasPrev} onClick={() => setPage(page - 1)}>Previous</button><button className={secondary} disabled={!meta.hasNext} onClick={() => setPage(page + 1)}>Next</button></div></div>}</section>
    {modal === 'role' && <Modal title={editingRole ? 'Edit access role' : 'Create access role'} close={() => { setModal(null); setEditingRole(null); }}><form onSubmit={saveRole} className="space-y-4 p-6"><Field label="Role name" value={roleForm.name} change={(name) => setRoleForm({ ...roleForm, name })} /><Field label="Description" value={roleForm.description} change={(description) => setRoleForm({ ...roleForm, description })} /><PermissionPicker catalog={permissions} selected={roleForm.permissions} change={(permissions) => setRoleForm({ ...roleForm, permissions })} /><Footer close={() => { setModal(null); setEditingRole(null); }} label={editingRole ? 'Save changes' : 'Create role'} /></form></Modal>}
    {modal === 'invite' && <Modal title="Invite a user" close={() => setModal(null)}><form onSubmit={invite} className="space-y-4 p-6"><p className="-mt-2 text-sm text-slate-500">A secure single-use password setup link will be emailed.</p><Field label="Full name" value={inviteForm.name} change={(name) => setInviteForm({ ...inviteForm, name })} /><Field label="Work email" type="email" value={inviteForm.email} change={(email) => setInviteForm({ ...inviteForm, email })} /><label className="block text-sm font-semibold">Role<select required className={input} value={inviteForm.accessRoleId} onChange={(e) => selectRole(e.target.value)}><option value="">Select role</option>{roles.filter((x) => !x.isSystem).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><PermissionPicker catalog={permissions} selected={inviteForm.permissions} change={(permissions) => setInviteForm({ ...inviteForm, permissions })} /><Footer close={() => setModal(null)} label="Send invitation" /></form></Modal>}</main>;
}
function Footer({ label, close }: { label: string; close: () => void }) { return <div className="flex justify-end gap-2 border-t pt-5"><button type="button" className={secondary} onClick={close}>Cancel</button><button className={primary}>{label}</button></div>; }
function PermissionPicker({ catalog, selected, change }: { catalog: Permission[]; selected: string[]; change: (permissions: string[]) => void }) { const groups = catalog.reduce<Record<string, Permission[]>>((all, item) => ({ ...all, [item.group]: [...(all[item.group] ?? []), item] }), {}); return <section><div className="mb-3 flex justify-between"><div><h3 className="text-sm font-bold">Tenant portal permissions</h3><p className="text-xs text-slate-500">Choose what this tenant can access after login.</p></div><span className="text-xs font-semibold text-[#0C5A69]">{selected.length} selected</span></div><div className="max-h-80 space-y-3 overflow-y-auto rounded-xl border p-3">{Object.entries(groups).map(([group, items]) => <div key={group}><b className="text-xs uppercase text-slate-500">{group}</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{items.map((item) => <label key={item.key} className="flex gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={selected.includes(item.key)} onChange={() => change(selected.includes(item.key) ? selected.filter((x) => x !== item.key) : [...selected, item.key])} /><span><b className="block">{item.label}</b>{item.description}</span></label>)}</div></div>)}{!catalog.length && <p className="text-sm text-slate-500">Loading permissions…</p>}</div></section>; }
