import { AlertTriangle, CheckCircle2, Clock3, Star, Ticket, UserRoundX } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adminApi, adminError, type AdminTicketDashboard } from "../api/admin.api";

const statusName = (value: string) => value.replaceAll("_", " ");
function Card({ label, value, note, icon }: { label: string; value: number | string; note: string; icon: React.ReactNode }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-slate-600">{label}</p><span className="text-[#0C5A69]">{icon}</span></div><p className="mt-4 text-3xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></section>;
}
export default function AdminTicketsDashboardPage() {
  const [data, setData] = useState<AdminTicketDashboard | null>(null);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); setData(await adminApi.ticketDashboard()); } catch (cause) { setError(adminError(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (!data && !error) return <main className="p-8 text-slate-500">Loading ticket dashboard...</main>;
  if (!data) return <main className="p-8 text-red-700">{error} <button onClick={() => void load()} className="underline">Retry</button></main>;
  const max = Math.max(1, ...data.daily.map((day) => day.total));
  const satisfaction = data.metrics.satisfaction;
  return <main className="mx-auto max-w-7xl space-y-5 p-5 sm:p-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#0C5A69]">Support operations</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Tickets Dashboard</h1><p className="mt-1 text-sm text-slate-500">Live platform-wide ticket activity and support workload.</p></div><Link to="/admin/tickets" className="rounded-lg bg-[#0C5A69] px-4 py-2 text-sm font-semibold text-white">View all tickets</Link></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card label="Open tickets" value={data.metrics.open} note="New tickets not yet assigned" icon={<Ticket size={19} />} /><Card label="Active tickets" value={data.metrics.active} note="All open support work" icon={<Clock3 size={19} />} /><Card label="Pending response" value={data.metrics.pendingResponse} note="Waiting for user or team" icon={<Clock3 size={19} />} /><Card label="Unassigned" value={data.metrics.unassigned} note="Active tickets needing an owner" icon={<UserRoundX size={19} />} /><Card label="Overdue" value={data.metrics.overdue} note="Past SLA resolution date" icon={<AlertTriangle size={19} />} /></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h2 className="font-bold">Tickets by day</h2><p className="mt-1 text-xs text-slate-500">Created and resolved in the last seven days.</p>{data.total === 0 ? <p className="py-16 text-center text-sm text-slate-500">No ticket activity yet.</p> : <div className="mt-7 grid h-52 grid-cols-7 items-end gap-3 border-b border-slate-100">{data.daily.map((day) => <div key={day._id} className="flex h-full flex-col justify-end text-center"><span className="mb-2 text-xs font-bold">{day.total}</span><div className="relative h-full"><div style={{ height: `${Math.round((day.total / max) * 100)}%` }} className="absolute bottom-0 w-full rounded-t bg-[#0C5A69]" /><div style={{ height: `${Math.round((day.resolved / max) * 100)}%` }} className="absolute bottom-0 w-full rounded-t bg-emerald-500" /></div><span className="mt-2 text-[10px] text-slate-500">{new Date(day._id + "T00:00:00").toLocaleDateString(undefined, { weekday: "short" })}</span></div>)}</div>}</div>
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">My queue</h2><p className="mt-1 text-xs text-slate-500">Active tickets assigned to you: {data.metrics.assignedToMe}</p><div className="mt-5 space-y-3">{data.myQueue.map((ticket) => <Link key={ticket.id} to={`/admin/tickets/${ticket.id}`} className="block rounded-lg border border-slate-100 p-3 hover:bg-slate-50"><p className="text-xs font-bold text-[#0C5A69]">#{ticket.ticketNumber}</p><p className="mt-1 truncate text-sm font-semibold">{ticket.title}</p><p className="mt-1 text-xs capitalize text-slate-500">{statusName(ticket.status)}</p></Link>)}{!data.myQueue.length && <p className="py-8 text-center text-sm text-slate-500">No active tickets assigned to you.</p>}</div></div></section>
    <section className="grid gap-5 lg:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Queue overview</h2><div className="mt-4 space-y-3">{data.categories.length ? data.categories.map((category) => <div key={category._id}><div className="flex justify-between text-sm"><span className="capitalize">{statusName(category._id)}</span><span>{category.open} open / {category.total}</span></div><div className="mt-1.5 h-1.5 rounded bg-slate-100"><div className="h-full rounded bg-[#0C5A69]" style={{ width: `${Math.round(category.open / Math.max(1, category.total) * 100)}%` }} /></div></div>) : <p className="py-8 text-center text-sm text-slate-500">No queues yet.</p>}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Status distribution</h2><div className="mt-4 space-y-2">{Object.entries(data.statuses).length ? Object.entries(data.statuses).map(([status, count]) => <div key={status} className="flex justify-between text-sm"><span className="capitalize text-slate-600">{statusName(status)}</span><strong>{count}</strong></div>) : <p className="py-8 text-center text-sm text-slate-500">No ticket data yet.</p>}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Resolution health</h2><div className="mt-4 space-y-3 text-sm"><p>Resolved this week <strong className="float-right">{data.metrics.resolvedThisWeek}</strong></p><p>Escalated <strong className="float-right">{data.metrics.escalated}</strong></p><p>Average first response <strong className="float-right">{data.metrics.averageFirstResponseMinutes === null ? "—" : `${data.metrics.averageFirstResponseMinutes}m`}</strong></p><p className="flex items-center gap-2 text-emerald-700"><CheckCircle2 size={16} /> Metrics update from live ticket data.</p></div></div></section>
    <section className="rounded-xl border border-amber-200 bg-amber-50/40 p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">My customer rating</h2><p className="mt-1 text-xs text-slate-500">Ratings for tickets you resolved.</p></div>{satisfaction.averageRating !== null && <div className="flex items-center gap-2"><Star size={24} className="fill-amber-400 text-amber-400" /><strong className="text-2xl">{satisfaction.averageRating.toFixed(1)}</strong><span className="text-sm text-slate-500">/ 5</span></div>}</div>
      {satisfaction.averageRating === null ? <p className="py-6 text-sm text-slate-500">No tenant ratings yet.</p> : <><p className="mt-4 text-sm text-slate-700"><strong>{satisfaction.ratedTickets}</strong> ratings from <strong>{satisfaction.resolvedTickets}</strong> tickets you resolved.</p><div className="mt-4 grid gap-2 sm:grid-cols-5">{[5, 4, 3, 2, 1].map((stars) => <div key={stars} className="flex items-center gap-2 text-xs"><span>{stars} star</span><div className="h-1.5 flex-1 rounded bg-amber-100"><div className="h-full rounded bg-amber-400" style={{ width: `${Math.round(((satisfaction.distribution[stars as 1 | 2 | 3 | 4 | 5] ?? 0) / Math.max(1, satisfaction.ratedTickets)) * 100)}%` }} /></div><strong>{satisfaction.distribution[stars as 1 | 2 | 3 | 4 | 5] ?? 0}</strong></div>)}</div></>}
    </section>  </main>;
}
