import InstructorAssignmentsPanel from '../components/InstructorAssignmentsPanel';
import { useEffect, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useSelector } from 'react-redux';
import type { RootState } from '../../../store';
import { instructorsApi, instructorError, instructorTypeLabels, type Instructor } from '../api/instructors.api';

const tabs = ['Overview', 'Course & Access', 'Engagement', 'Performance'] as const;
const field = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
function Card({ title, children, className = '' }: { title: string; children: ReactNode; className?: string }) {
  return <section className={`rounded-xl border border-slate-200 bg-white p-5 ${className}`}><h2 className="mb-3 text-sm font-semibold text-slate-900">{title}</h2>{children}</section>;
}
function Metric({ title, value, note }: { title: string; value: ReactNode; note: string }) {
  return <Card title={title}><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></Card>;
}
function Empty({ children }: { children: ReactNode }) { return <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">{children}</p>; }
function date(value?: string | null) { return value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeZone: 'Asia/Kolkata' }).format(new Date(value)) : 'Not provided'; }
export default function InstructorDetailsPage() {
  const { id } = useParams();
  const user = useSelector((state: RootState) => state.auth.user);
  const canManage = !!(user?.isOwner || user?.permissions?.includes('member:manage'));
  const [record, setRecord] = useState<Instructor | null>(null);
  const [tab, setTab] = useState<typeof tabs[number]>('Overview');
  const [course, setCourse] = useState('');
  const [cohort, setCohort] = useState('');
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const [error, setError] = useState('');
  const [retry, setRetry] = useState(0);
  useEffect(() => {
    let active = true;
    if (id) void instructorsApi.get(id).then(value => { if (active) { setRecord(value); setError(''); } }).catch(reason => { if (active) setError(instructorError(reason)); });
    return () => { active = false; };
  }, [id, retry]);
  if (error) return <div role="alert" className="p-8 text-red-700">{error} <button onClick={() => setRetry(value => value + 1)} className="underline">Retry</button><Link to="/partner/instructors" className="ml-4 underline">All instructors</Link></div>;
  if (!record || record.id !== id) return <p role="status" className="p-8">Loading instructor details...</p>;
  const profile = record.instructorProfile;
  const assignments = record.assignments ?? [];
  const courses = [...new Map(assignments.map(item => [item.courseId, item.courseTitle])).entries()];
  const filtered = assignments.filter(item => (!course || item.courseId === course) && (!cohort || item.id === cohort));
  const role = record.teachingRole === 'co_instructor' ? 'Co-instructor' : 'Instructor';
  const filters = <div className="mb-5 grid gap-4 sm:grid-cols-3"><label className="text-xs text-slate-600">Course<select value={course} onChange={event => { setCourse(event.target.value); setCohort(''); }} className={`mt-2 ${field}`}><option value="">All assigned courses ({courses.length})</option>{courses.map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label><label className="text-xs text-slate-600">Cohort<select value={cohort} onChange={event => setCohort(event.target.value)} className={`mt-2 ${field}`}><option value="">All assigned cohorts</option>{assignments.filter(item => !course || item.courseId === course).map(item => <option key={item.id} value={item.id}>{item.cohort}</option>)}</select></label><label className="text-xs text-slate-600">Activity period<input type="month" value={period} onChange={event => setPeriod(event.target.value)} className={`mt-2 ${field}`} /></label></div>;
  return <main className="mx-auto max-w-7xl px-5 py-6 text-slate-900">
    <Link to="/partner/instructors" className="text-sm text-[#0C5A69]">← All instructors</Link>
    <header className="my-5 flex items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Instructor details</h1><p className="mt-1 text-sm text-slate-500">Profile, teaching scope and recent activity for {record.name}.</p></div>{canManage && !record.archivedAt && <Link to={`/partner/instructors/${record.id}/edit`} className="rounded-lg border bg-white px-4 py-2 text-sm">Edit Profile</Link>}</header>
    <div className="flex items-center gap-4 rounded-xl border bg-white p-5"><div aria-hidden="true" className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-teal-50 font-bold text-[#0C5A69]">{record.name.split(' ').map(part => part[0]).slice(0, 2).join('')}</div><div><h2 className="font-semibold">{record.name}</h2><p className="mt-1 text-xs text-slate-600">{instructorTypeLabels[profile.employment.type]} · {profile.specialty}</p><p className="mt-1 text-xs text-slate-500">{record.email} · {role}</p></div><span className="ml-auto rounded bg-teal-50 px-3 py-1 text-xs capitalize text-[#0C5A69]">{record.archivedAt ? 'Archived' : record.status}</span></div>
    <nav aria-label="Instructor details tabs" className="my-5 flex overflow-x-auto border-b">{tabs.map(value => <button key={value} aria-current={tab === value ? 'page' : undefined} onClick={() => setTab(value)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm ${tab === value ? 'border-[#0C5A69] font-semibold text-[#0C5A69]' : 'border-transparent text-slate-500'}`}>{value}</button>)}</nav>
    {tab === 'Overview' && <><div className="mb-5 grid gap-4 sm:grid-cols-3"><Metric title="Assigned courses" value={record.courseCount} note={`${assignments.length} cohorts · ${record.plannedCourseCount} planned courses`} /><Metric title="Assigned learners" value={record.learnerCount} note="Unique learners across assigned cohorts" /><Metric title="Instructor rating" value="—" note="No rating data available" /></div><div className="grid gap-5 md:grid-cols-3"><Card title="Contact & expertise"><dl className="space-y-4 text-sm">{[['Email', record.email], ['Phone', record.phone || 'Not provided'], ['Specialty', profile.specialty], ['Expertise', profile.expertise || 'Not provided'], ['Bio', record.bio || 'Not provided'], ['Employment type', instructorTypeLabels[profile.employment.type]], ['Joined', date(record.createdAt)], ['Employment start', date(profile.employment.startDate)], ['Renewal note', profile.employment.renewalNote || 'Not provided'], ['Engagement end', profile.employment.endDate ? date(profile.employment.endDate) : 'Ongoing'], ['Last active', date(record.lastActiveAt)]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl></Card><div className="space-y-5 md:col-span-2"><Card title="Assigned courses">{assignments.length ? assignments.map(item => <div key={item.id} className="mb-3 rounded-lg border p-3"><p className="text-sm font-semibold">{item.courseTitle}</p><p className="mt-1 text-xs text-slate-500">{item.cohort} · {item.teachingRole === 'instructor' ? 'Instructor' : 'Co-instructor'} · {item.learnerCount} learners</p></div>) : <Empty>No actual teaching assignments yet. Planned assignments are separate.</Empty>}<button onClick={() => setTab('Course & Access')} className="mt-3 text-sm text-[#0C5A69]">Manage courses & access →</button></Card><Card title="Recent activity">{record.recentActivity?.length ? <ul className="divide-y divide-slate-100">{record.recentActivity.map((item, index) => <li key={item.type + item.occurredAt + index} className="py-3"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-slate-500">{[item.courseTitle, item.cohort].filter(Boolean).join(' ? ')}</p><time dateTime={item.occurredAt} className="mt-1 block text-xs text-slate-500">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' }).format(new Date(item.occurredAt))} IST</time></li>)}</ul> : <Empty>No recorded login, content or announcement activity yet.</Empty>}</Card></div></div></>}
    {tab === 'Course & Access' && <InstructorAssignmentsPanel record={record} canManage={canManage} onChanged={async () => { if (id) setRecord(await instructorsApi.get(id)); }} />}
    {tab === 'Engagement' && <>{filters}<div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Active days', 'Teaching activity is not tracked'], ['Sessions delivered', 'No session activity source'], ['Grading turnaround', 'No grading timestamps available'], ['First response time', 'No instructor response metrics available']].map(([title, note]) => <Metric key={title} title={title} value="—" note={note} />)}</div><div className="mb-5 grid gap-5 md:grid-cols-3"><Card title="Active days by week" className="md:col-span-2"><Empty>No recorded activity for {period || 'the selected period'}. Weekly bars will require teaching activity records.</Empty></Card><Card title="Activity context"><p className="text-xs text-slate-500">Last active / recorded login</p><p className="my-2 text-sm">{date(record.lastActiveAt)}</p><p className="text-xs text-slate-500">A login is separate from teaching activity. Teaching sessions, grading and discussions need their own event records.</p></Card></div><Card title="Recent activity in period"><Empty>No teaching activity records for the selected course, cohort and period.</Empty></Card></>}
    {tab === 'Performance' && <>{filters}<div className="mb-5 grid gap-4 sm:grid-cols-3"><Metric title="Course completion" value="—" note="Completion records are not available" /><Metric title="Assessment pass rate" value="—" note="Assessment outcomes are not available" /><Metric title="Instructor rating" value="—" note="No learner reviews available" /></div><Card title="Course-level outcomes"><div className="overflow-x-auto"><table className="w-full min-w-[550px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Course / cohort', 'Completion', 'Assessment pass rate', 'Instructor feedback'].map(label => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{filtered.map(item => <tr key={item.id} className="border-b"><td className="p-3">{item.courseTitle}<p className="text-xs text-slate-500">{item.cohort}</p></td><td className="p-3">—</td><td className="p-3">—</td><td className="p-3">No reviews</td></tr>)}</tbody></table></div>{!filtered.length && <Empty>No assigned courses match these filters.</Empty>}<p className="mt-3 text-xs text-slate-500">Unavailable outcomes are not counted as zero.</p></Card><div className="mt-5 grid gap-5 md:grid-cols-3"><Card title="Learner feedback" className="md:col-span-2"><Empty>No learner feedback source is connected.</Empty></Card><Card title="Read these results in context"><p className="text-sm text-slate-500">Compare outcomes within the same course, cohort and reporting period. Engagement and ratings measure different things.</p><button onClick={() => setTab('Engagement')} className="mt-4 text-sm text-[#0C5A69]">View instructor activity →</button></Card></div></>}
  </main>;
}
